### ISSUE TITLE
Provide User with valid range of lat/lng inputs before entering.

### ISSUE THREAD

**Issue by peterdaly13** [piedras77/centralized_smart_dashboard#17]
It took us a while to figure out the valid range allowed for latitude and longitude, because it only ever tells us if it is out of range but never what that range is. You could put the valid range in parentheses next to the Latitude and Longitude text.

Severity: Enhancement

**Comment by yuanchenGH** [comment]
Latitudes range from -90 to 90 and Longitudes range from -180 to 180. We were able to create coordinates 100, 100. The app should treat it as a invalid input and give the user a warning instead of adding it to the map.

**Comment by bkinder2385** [comment]
Thank you for catching that! We've changed the boundaries to reflect the correct ranges.
