### ISSUE TITLE
Confusion regarding AI Nav/ERDM Distinction

### ISSUE THREAD

**Issue by peterdaly13** [piedras77/centralized_smart_dashboard#18]
Is there a relevant difference between AI Nav and ERDM? When we add coordinates to one they appear in the other and it doesn't seem that either one contains functionality that the other doesn't.

Severity: Clarification

**Comment by WillDaru22** [comment]
For the purposes of design the pages would appear functionally similar however the client requested the pages as they will be using them in different ways.  AI Navigation is made for autonomous movement of the rover whereas ERDM is more of a visual aid for the user manually controlling and moving the rover.
